language: node_js
sudo: false
node_js:
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11

os:
  - linux
  - osx
script:
  - npm run test-with-coverage
  - npm run lint
after_success:
  - npm run codecov -- -f coverage/lcov.info

notifications:
  email: false
