environment:
  matrix:
    - nodejs_version: '11'
    - nodejs_version: '10'
    - nodejs_version: '9'
    - nodejs_version: '8'
    - nodejs_version: '7'
    - nodejs_version: '6'

version: '{build}'

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - npm install

matrix:
  fast_finish: false

# No need for MSBuild on this project
build: off

test_script:
  - npm run test-with-coverage
  - npm run lint

on_success:
  - npm run codecov -- -f coverage/lcov.info
